file_format: "1"
id: optimag
name: Optimag
type: shield
url: https://keeb.io/products/bfo-9000-keyboard-customizable-full-size-split-ortholinear
requires: [pro_micro]
features:
  - keys
siblings:
  - optimag_left
  - optimag_right
